Bumbo.Web/Models/Prognoses/PrognoseViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Bumbo.Data.Models
{
    public partial class PrognoseViewModel
    {
        [Required]
        public DateTime Date { get; set; }
        [Required]
        [Range(0, Int32.MaxValue)]
        public int AmountOfCustomers { get; set; }
        [Required]
        [Range(0, 999999999999)]
        public int AmountOfFreight { get; set; }
        [Required]
        public int BranchId { get; set; }
        [Required]
        public string WeatherDescription { get; set; }
        public virtual Branch Branch { get; set; }

        public string Holiday { get; set; }
        public int LastYearVisitors { get; set; }
        public int LastWeekVisitors { get; set; }

        public string GetFormattedDate()
        {
            string day = (Date.Day < 10) ? "0" + Date.Day.ToString() : Date.Day.ToString();
            string month = (Date.Month < 10) ? "0" + Date.Month.ToString() : Date.Month.ToString();

            return day + "-" + month + "-" + Date.Year;
        }

        public int GetEstimatedWorkingHours()
        {
            var freight = this.AmountOfFreight / 100;
            var customers = this.AmountOfCustomers;

            switch (WeatherDescription)
            {
                case "regen":
                    customers = (int)Math.Floor((double)customers * 0.7);
                    break;
                case "zon":
                    customers = (int)Math.Floor((double)customers * 1.2);
                    break;
                case "bewolkt":
                    customers = (int)Math.Floor((double)customers * 0.9);
                    break;
                case "storm":
                    customers = (int)Math.Floor((double)customers * 0.6);
                    break;
                default:
                    break;
            }

            customers /= 50;

            var estimated = customers * freight;

            return estimated < 5 ? 5 : estimated;
        }

        public string GetDayName()
        {
            var culture = new System.Globalization.CultureInfo("nl-NL");

            return culture.TextInfo.ToTitleCase(culture.DateTimeFormat.GetDayName(Date.DayOfWeek)); ;
        }
    }
}

Bumbo.Web/Models/Prognoses/PrognosesViewModel.cs
using Bumbo.Data.Models;
using System.Collections.Generic;

namespace Bumbo.Web.Models
{
    public class PrognosesViewModel
    {
        public List<PrognoseViewModel> Prognoses { get; set; }
    }
}

Bumbo.Web/Models/User/CreateViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Bumbo.Web.Models
{
    public class CreateViewModel : UserViewModel
    {
        [DataType(DataType.Password, ErrorMessage = "Wachtwoord voldoet niet aan de eisen")]
        [Required]
        public string Password { get; set; }
    }
}

Bumbo.Web/Controllers/PrognosesController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Bumbo.Data.Models;
using Bumbo.Data.Repository;
using Bumbo.Web.Models;
using System;
using Bumbo.Data;
using System.Globalization;
using System.Text.RegularExpressions;
using Nager.Date;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace Bumbo.Web.Controllers
{
    public class PrognosesController : Controller
    {
        private readonly IPrognosesRepository _repository;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;

        public PrognosesController(ApplicationDbContext context, UserManager<User> userManager, IPrognosesRepository repository)
        {
            _context = context;
            _userManager = userManager;
            _repository = repository;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            var jan1 = new DateTime(DateTime.Today.Year, 1, 1);
            var startOfFirstWeek = jan1.AddDays(1 - (int)(jan1.DayOfWeek));
            var weeks =
                Enumerable
                    .Range(0, 54)
                    .Select(i => new
                    {
                        weekStart = startOfFirstWeek.AddDays(i * 7)
                    })
                    .TakeWhile(x => x.weekStart.Year <= jan1.Year)
                    .Select(x => new
                    {
                        x.weekStart,
                        weekFinish = x.weekStart.AddDays(6)
                    })
                    .SkipWhile(x => x.weekFinish < jan1.AddDays(1))
                    .Select((x, i) => new
                    {
                        Van = x.weekStart.ToShortDateString(),
                        Tot = x.weekFinish.ToShortDateString(),
                        //WeekNummer = i + 1
                    });


            ViewBag.HasPrognoses = HasPrognoses(weeks, user.BranchId);

            ViewBag.Weeks = weeks;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> IndexPrognoses(string week)
        {
            week = Regex.Replace(week, "[^0-9]+", string.Empty);
            int weekNr = Int32.Parse(week);

            DateTime start = FirstDateOfWeek(DateTime.Now.Year, weekNr, CultureInfo.CurrentCulture);
            DateTime end = start.AddDays(6);

            var jan1 = new DateTime(DateTime.Today.Year, 1, 1);
            var startOfFirstWeek = jan1.AddDays(1 - (int)(jan1.DayOfWeek));
            var weeks =
                Enumerable
                    .Range(0, 54)
                    .Select(i => new
                    {
                        weekStart = startOfFirstWeek.AddDays(i * 7)
                    })
                    .TakeWhile(x => x.weekStart.Year <= jan1.Year)
                    .Select(x => new
                    {
                        x.weekStart,
                        weekFinish = x.weekStart.AddDays(6)
                    })
                    .SkipWhile(x => x.weekFinish < jan1.AddDays(1))
                    .Select((x, i) => new
                    {
                        Van = x.weekStart.ToShortDateString(),
                        Tot = x.weekFinish.ToShortDateString(),
                        //WeekNummer = i + 1
                    });

            var user = await _userManager.GetUserAsync(User);
            var branchId = user.BranchId;

            ViewBag.BranchId = branchId;

            ViewBag.Weeks = weeks;
            ViewBag.Prognoses = _repository.GetAll(start, end, branchId);
            ViewBag.Start = start;
            ViewBag.End = end;

            ViewBag.HasPrognoses = HasPrognoses(weeks, user.BranchId);

            return View("Index");
        }

        private static DateTime FirstDateOfWeek(int year, int weekOfYear, CultureInfo ci)
        {
            DateTime jan1 = new DateTime(year, 1, 1);
            int daysOffset = (int)ci.DateTimeFormat.FirstDayOfWeek - (int)jan1.DayOfWeek;
            DateTime firstWeekDay = jan1.AddDays(daysOffset);
            int firstWeek = ci.Calendar.GetWeekOfYear(jan1, ci.DateTimeFormat.CalendarWeekRule, ci.DateTimeFormat.FirstDayOfWeek);
            if ((firstWeek <= 1 || firstWeek >= 52) && daysOffset >= -4)
            {
                weekOfYear -= 1;
            }
            return firstWeekDay.AddDays(weekOfYear * 7);
        }

        [HttpPost]
        public IActionResult Create(DateTime start, int branchId)
        {
            var prognoses = new List<PrognoseViewModel>();

            for (int i = 0; i < 7; i++)
            {
                var prognoseDate = start.AddDays(i);
                prognoses.Add(
                    new PrognoseViewModel()
                    {
                        Date = prognoseDate,
                        BranchId = branchId,
                        LastWeekVisitors = _repository.Get(prognoseDate.AddDays(-7), branchId)?.AmountOfCustomers ?? 0,
                        LastYearVisitors = _repository.Get(prognoseDate.AddYears(-1), branchId)?.AmountOfCustomers ?? 0
                    }
                );

                //Handle holidays
                if (DateSystem.IsPublicHoliday(prognoses[i].Date, CountryCode.NL))
                {
                    var holidays = DateSystem.GetPublicHoliday(prognoses[i].Date, prognoses[i].Date, CountryCode.NL);
                    foreach (var publicHoliday in holidays)
                    {
                        prognoses[i].Holiday = publicHoliday.LocalName;
                    }
                }
            }

            PrognosesViewModel viewModel = new PrognosesViewModel()
            {
                Prognoses = prognoses
            };

            ViewBag.Branches = _context.Branch.ToList();


            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Store(PrognosesViewModel model)
        {
            var user = await _userManager.GetUserAsync(User);

            foreach (var prognoseViewModel in model.Prognoses)
            {
                if (prognoseViewModel.Date != null && prognoseViewModel.BranchId != 0)
                {
                    if (prognoseViewModel.BranchId != user.BranchId) return Unauthorized();

                    Prognoses prognose = new Prognoses
                    {
                        Date = prognoseViewModel.Date,
                        AmountOfCustomers = prognoseViewModel.AmountOfCustomers,
                        AmountOfFreight = prognoseViewModel.AmountOfFreight,
                        BranchId = prognoseViewModel.BranchId,
                        WeatherDescription = prognoseViewModel.WeatherDescription,
                        Branch = prognoseViewModel.Branch
                    };

                    var exists = await _context.Prognoses
                        .Where(p => p.Date == prognose.Date)
                        .AnyAsync();

                    if (exists)
                        _repository.Update(prognose);

                    if (!_repository.Create(prognose)) return View("Create", model);
                }
                else
                {
                    return View("Create", model);
                }
            }


            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Edit(DateTime start, int branchId)
        {
            var prognoses = new List<PrognoseViewModel>();

            for (int i = 0; i < 7; i++)
            {
                var prognoseDate = start.AddDays(i);
                var prog = _repository.Get(prognoseDate, branchId);
                if (prog != null)
                {
                    prognoses.Add(
                    new PrognoseViewModel()
                    {
                        Date = prog.Date,
                        BranchId = branchId,
                        AmountOfCustomers = prog.AmountOfCustomers,
                        AmountOfFreight = prog.AmountOfFreight,
                        WeatherDescription = prog.WeatherDescription,
                        LastWeekVisitors = _repository.Get(prognoseDate.AddDays(-7), branchId)?.AmountOfCustomers ?? 0,
                        LastYearVisitors = _repository.Get(prognoseDate.AddYears(-1), branchId)?.AmountOfCustomers ?? 0

                    });

                    //Handle holidays
                    if (DateSystem.IsPublicHoliday(prognoses[i].Date, CountryCode.NL))
                    {
                        var holidays = DateSystem.GetPublicHoliday(prognoses[i].Date, prognoses[i].Date, CountryCode.NL);
                        foreach (var publicHoliday in holidays)
                        {
                            prognoses[i].Holiday = publicHoliday.LocalName;
                        }
                    }
                }
            }

            PrognosesViewModel viewModel = new PrognosesViewModel()
            {
                Prognoses = prognoses
            };
            ViewBag.Branches = _context.Branch.ToList();
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Update(PrognosesViewModel model)
        {
            var user = await _userManager.GetUserAsync(User);

            foreach (var prognoseViewModel in model.Prognoses)
            {
                if (prognoseViewModel.Date != null && prognoseViewModel.BranchId != 0)
                {
                    if (prognoseViewModel.BranchId != user.BranchId) return Unauthorized();

                    Prognoses prognose = new Prognoses
                    {
                        Date = prognoseViewModel.Date,
                        AmountOfCustomers = prognoseViewModel.AmountOfCustomers,
                        AmountOfFreight = prognoseViewModel.AmountOfFreight,

Bumbo.Web/Views/Prognoses/Create.cshtml
@model Bumbo.Web.Models.PrognosesViewModel

@{
    ViewData["Title"] = "Create";
}

<h4>Maak nieuwe verwachting</h4>
<hr />
<div class="row mb-3">
    <div class="col-12">
        <a class="btn btn-primary" asp-action="Index"><i class="fas fa-chevron-left mr-2"></i>Go back</a>
    </div>
</div>
<div class="row">
    <div>
        <form asp-action="Store" asp-controller="Prognoses" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            @for (int i = 0; i < Model.Prognoses.Count; i++)
            {
                <div class="row">
                    <div class="card my-4 col-8 px-0">
                        <div class="card-header">
                            <strong>@Model.Prognoses[i].GetDayName() | @Model.Prognoses[i].Date.ToShortDateString()</strong>
                        </div>
                        <div class="form-row card-body">
                            <div class="form-group col-md-6">
                                <label asp-for="@Model.Prognoses[i].AmountOfCustomers" class="control-label">Verwacht aantal bezoekers</label>
                                <input min="0" asp-for="@Model.Prognoses[i].AmountOfCustomers" class="form-control customerAmount" />
                                <span asp-validation-for="@Model.Prognoses[i].AmountOfCustomers" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-6">
                                <label asp-for="@Model.Prognoses[i].AmountOfFreight" class="control-label">Verwachte hoeveelheid vracht</label>
                                <input min="0" asp-for="@Model.Prognoses[i].AmountOfFreight" class="form-control freightAmount" />
                                <span asp-validation-for="@Model.Prognoses[i].AmountOfFreight" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-6">
                                <label asp-for="@Model.Prognoses[i].WeatherDescription" class="control-label mx-1">
                                    <i class="fas fa-cloud-showers-heavy"></i>
                                    <input asp-for="@Model.Prognoses[i].WeatherDescription" value="regen" type="radio" class="form-control weather" />
                                </label>
                                <label asp-for="@Model.Prognoses[i].WeatherDescription" class="control-label mx-1">
                                    <i class="fas fa-sun"></i>
                                    <input asp-for="@Model.Prognoses[i].WeatherDescription" value="zon" type="radio" class="form-control weather" />
                                </label>
                                <label asp-for="@Model.Prognoses[i].WeatherDescription" class="control-label mx-1">
                                    <i class="fas fa-cloud-sun"></i>
                                    <input asp-for="@Model.Prognoses[i].WeatherDescription" value="bewolkt" type="radio" class="form-control weather" />
                                </label>
                                <label asp-for="@Model.Prognoses[i].WeatherDescription" class="control-label mx-1">
                                    <i class="fas fa-bolt"></i>
                                    <input asp-for="@Model.Prognoses[i].WeatherDescription" value="storm" type="radio" class="form-control weather" />
                                </label>

                                <span asp-validation-for="@Model.Prognoses[i].WeatherDescription" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-6">
                                <label class="control-label">Te maken arbeidsuren</label>
                                <input id="workingHours" class="form-control disabled" />
                            </div>
                        </div>
                    </div>
                    <input type="hidden" asp-for="@Model.Prognoses[i].BranchId"/>
                    <input type="hidden" asp-for="@Model.Prognoses[i].Date"/>
                    <div class="col-4 my-4">
                        @if (Model.Prognoses[i].LastWeekVisitors != 0)
                        {
                            <div class="p-2 border rounded">
                                <p>Bezoekers vorige week:</p>
                                <h4>@Model.Prognoses[i].LastWeekVisitors</h4>
                            </div>
                        }
                        @if (Model.Prognoses[i].LastYearVisitors != 0)
                        {
                            <div class="p-2 border rounded">
                                <p>Bezoekers vorig jaar:</p>
                                <h4>@Model.Prognoses[i].LastYearVisitors</h4>
                            </div>
                        }
                        @if (Model.Prognoses[i].Holiday != null)
                        {
                            <div class="p-2 border rounded">
                                <p>Houd rekening met</p>
                                <h4>@Model.Prognoses[i].Holiday</h4>
                            </div>
                        }
                    </div>
                </div>
            }

            <div class="form-group">
                <input type="submit" value="Aanmaken" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Bumbo.Web/Views/Prognoses/Edit.cshtml
@model Bumbo.Web.Models.PrognosesViewModel

@{
    ViewData["Title"] = "Edit";
}

<h4>Wijzig verwachting</h4>
<hr />
<div class="row mb-3">
    <div class="col-12">
        <a class="btn btn-primary" asp-action="Index"><i class="fas fa-chevron-left mr-2"></i>Go back</a>
    </div>
</div>
<div class="row">
    <div>
        <form asp-action="Update" asp-controller="Prognoses" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            @for (int i = 0; i < Model.Prognoses.Count; i++)
            {
                <div class="row">
                    <div class="card my-4 col-8 px-0">

                        <div class="card-header">
                            <strong>@Model.Prognoses[i].Date.ToShortDateString()</strong>
                        </div>

                        <div class="form-row card-body">
                            <div class="form-group col-md-6">
                                <label asp-for="@Model.Prognoses[i].AmountOfCustomers" class="control-label">Verwacht aantal bezoekers</label>
                                <input min="0" asp-for="@Model.Prognoses[i].AmountOfCustomers" class="form-control customerAmount" />
                                <span asp-validation-for="@Model.Prognoses[i].AmountOfCustomers" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-6">
                                <label asp-for="@Model.Prognoses[i].AmountOfFreight" class="control-label">Verwachte hoeveelheid vracht</label>
                                <input min="0" asp-for="@Model.Prognoses[i].AmountOfFreight" class="form-control freightAmount" />
                                <span asp-validation-for="@Model.Prognoses[i].AmountOfFreight" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-6">
                                <label asp-for="@Model.Prognoses[i].WeatherDescription" class="control-label mx-1">
                                    <i class="fas fa-cloud-showers-heavy"></i>
                                    <input asp-for="@Model.Prognoses[i].WeatherDescription" value="regen" type="radio" class="form-control weather" />
                                </label>
                                <label asp-for="@Model.Prognoses[i].WeatherDescription" class="control-label mx-1">
                                    <i class="fas fa-sun"></i>
                                    <input asp-for="@Model.Prognoses[i].WeatherDescription" value="zon" type="radio" class="form-control weather" />
                                </label>
                                <label asp-for="@Model.Prognoses[i].WeatherDescription" class="control-label mx-1">
                                    <i class="fas fa-cloud-sun"></i>
                                    <input asp-for="@Model.Prognoses[i].WeatherDescription" value="bewolkt" type="radio" class="form-control weather" />
                                </label>
                                <label asp-for="@Model.Prognoses[i].WeatherDescription" class="control-label mx-1">
                                    <i class="fas fa-bolt"></i>
                                    <input asp-for="@Model.Prognoses[i].WeatherDescription" value="storm" type="radio" class="form-control weather" />
                                </label>

                                <span asp-validation-for="@Model.Prognoses[i].WeatherDescription" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-6">
                                <label class="control-label">Te maken arbeidsuren</label>
                                <input id="workingHours" readonly value="@Model.Prognoses[i].GetEstimatedWorkingHours()" class="form-control disabled" />
                            </div>
                        </div>
                    </div>

                    <input type="hidden" asp-for="@Model.Prognoses[i].BranchId" />
                    <input type="hidden" asp-for="@Model.Prognoses[i].Date" />

                    <div class="col-4 my-4">
                        @if (Model.Prognoses[i].LastWeekVisitors != 0)
                        {
                            <div class="p-2 border rounded">
                                <p>Bezoekers vorige week:</p>
                                <h4>@Model.Prognoses[i].LastWeekVisitors</h4>
                            </div>
                        }
                        @if (Model.Prognoses[i].LastYearVisitors != 0)
                        {
                            <div class="p-2 border rounded">
                                <p>Bezoekers vorig jaar:</p>
                                <h4>@Model.Prognoses[i].LastYearVisitors</h4>
                            </div>
                        }
                        @if (Model.Prognoses[i].Holiday != null)
                        {
                            <div class="p-2 border rounded">
                                <p>Houd rekening met</p>
                                <h4>@Model.Prognoses[i].Holiday</h4>
                            </div>
                        }
                    </div>
                </div>
            }

            <div class="form-group">
                <input type="submit" value="Wijzigen" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Bumbo.Web/Views/Prognoses/Index.cshtml
@using Bumbo.Data.Models

@{
    ViewData["Title"] = "Index";
}

<h1>Prognoses</h1>

<div class="row">
    <div class="col-4">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Weeknummer
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (ViewBag.Weeks != null)
                {
                    int i = 1; int y = 0;
                    @foreach (var week in ViewBag.Weeks)
                    {
                        <tr class=" @(ViewBag.HasPrognoses[y] == false ? "table-danger" : "")">
                            <td>
                                <form asp-action="IndexPrognoses" method="post" class="text-right d-inline-block position-relative float-right">
                                    <input type="hidden" name="week" value="@i">
                                    <label class="small mb-0">@week</label>
                                    <label class="mb-0 d-block" style="font-weight:600;">Weeknummer: @i</label>
                                    <button style="top:0" type="submit" class="btn pt-0 position-absolute d-block w-100 h-100"></button>
                                </form>
                            </td>
                        </tr>
                        i++; y++;
                    }
                }
            </tbody>

        </table>
    </div>

    <div class="col-8">
        <table class="table table-hover" style="table-layout:fixed;">
            <thead>
                <tr>
                    <th>
                        Prognose's
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (ViewBag.Prognoses != null)
                {
                    @if (ViewBag.Prognoses.Count > 0)
                    {
                        <tr>
                            <th class="border-top-0 w-50">
                                Datum
                            </th>
                            <th class="border-top-0">
                                Dag
                            </th>
                            <th class="border-top-0">
                                Aantal bezoekers
                            </th>
                            <th class="border-top-0">
                                Hoeveelheid vracht
                            </th>
                        </tr>
                        @foreach (Prognoses prog in ViewBag.Prognoses)
                        {
                            <tr>
                                <td>
                                    @prog.Date.ToShortDateString()
                                </td>
                                <td>
                                    @prog.GetDayName()
                                </td>
                                <td>
                                    @prog.AmountOfCustomers
                                </td>
                                <td>
                                    @prog.AmountOfFreight
                                </td>
                            </tr>
                        }
                        <tr class="nohover">
                            <td class="border-top-0" colspan="2">
                                <form asp-action="Edit" method="post" class="text-right d-inline-block mr-2">
                                    <input type="hidden" name="start" value="@ViewBag.Start">
                                    <input type="hidden" name="branchId" value="@ViewBag.BranchId">
                                    <button type="submit" class="btn btn-primary d-inline-block"><i class="fas fa-edit mr-2"></i>Bewerken</button>
                                </form>
                                <form asp-action="Delete" method="post" class="text-right d-inline-block verify-delete">
                                    <input type="hidden" name="start" value="@ViewBag.Start">
                                    <input type="hidden" name="branchId" value="@ViewBag.BranchId" />
                                    <button type="submit" class="btn btn-danger"><i class="fas fa-trash-alt mr-2"></i>Verwijderen</button>
                                </form>
                            </td>
                        </tr>

                    }
                    else
                    {
                        <tr>
                            <td>
                                <form asp-action="Create" method="post">
                                    <input type="hidden" name="start" value="@ViewBag.Start" />
                                    <input type="hidden" name="branchId" value="@ViewBag.BranchId" />
                                    <button type="submit" class="btn">Maak nieuwe verwachting</button>
                                </form>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td>
                            <p>Klik op een week op de verwachting te bekijken</p>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>