Bumbo.Web/Models/Schedule/ScheduleCreateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Bumbo.Data.Models;

namespace Bumbo.Web.Models
{
    public class ScheduleCreateViewModel
    {
        public List<AvailableWorktime> AvailableWorkTimes { get; set; }
        public List<PlannedWorktime> PlannedWorktimes { get; set; }
        public List<Prognoses> Prognoses { get; set; }
        public DateTime MinimumDate { get; set; }
        public DateTime MaximumDate { get; set; }
        public List<string> Errors { get; set; }
        public string UserName { get; set; }
        public int UserId { get; set; }
    }
}

Bumbo.Web/Models/Schedule/SchedulePlanViewModel.cs
using Bumbo.Data;
using Bumbo.Data.Models;
using System;
using System.Collections.Generic;

namespace Bumbo.Web.Models
{
    public class SchedulePlanViewModel
    {
        public IEnumerable<User> Users { get; set; }
        public DateTime Date { get; set; }
        public List<string> Errors { get; set; }
    }
}

Bumbo.Web/Models/Schedule/ScheduleResponseViewModel.cs
using Bumbo.Data;
using Bumbo.Data.Models;
using System;
using System.Collections.Generic;

namespace Bumbo.Web.Models
{
    public class ScheduleResponseViewModel
    {
        public DateTime Start { get; set; }
        public DateTime End { get; set; }
        public string Title { get; set; }
    }
}

Bumbo.Web/Models/Schedule/ScheduleViewModel.cs
using Bumbo.Data.Models;
using System;
using System.Collections.Generic;

namespace Bumbo.Web.Models
{
    public class ScheduleViewModel
    {
        public IEnumerable<User> Users { get; set; }
        public int UserId { get; set; }
    }
}

Bumbo.Web/Models/User/CreateViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Bumbo.Web.Models
{
    public class CreateViewModel : UserViewModel
    {
        [DataType(DataType.Password, ErrorMessage = "Wachtwoord voldoet niet aan de eisen")]
        [Required]
        public string Password { get; set; }
    }
}

Bumbo.Web/Controllers/ScheduleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Bumbo.Data;
using System.Threading.Tasks;
using System.Collections.Generic;
using Bumbo.Data.Models;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Bumbo.Web.Models;
using System;
using Bumbo.Data.Services;

namespace Bumbo.Web.Controllers
{
    [Authorize]
    public class ScheduleController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;
        private readonly ICAOService _caoService;

        public ScheduleController(ApplicationDbContext context, UserManager<User> userManager, ICAOService caoService)
        {
            _context = context;
            _userManager = userManager;
            _caoService = caoService;
        }

        public async Task<IActionResult> IndexAsync(ScheduleViewModel model)
        {
            var user = await _userManager.GetUserAsync(User);

            var newModel = new ScheduleViewModel
            {
                UserId = model.UserId != 0 ? model.UserId : user.Id,
                Users = User.IsInRole("Manager") ? await _context.Users.Where(u => u.BranchId == user.BranchId).ToListAsync() : null
            };

            return View(newModel);
        }

        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Plan(SchedulePlanViewModel model)
        {
            var user = await _userManager.GetUserAsync(User);
            var users = await _context.Users.Where(u => u.BranchId == user.BranchId).ToListAsync();
            var date = model.Date >= DateTime.Today ? model.Date : GetBeginningOfWeek(DateTime.Today);
            var errors = await CalculateMonthlyCAOAsync(users, date);
            
            var newModel = new SchedulePlanViewModel
            {
                Users = users,
                Date = date,
                Errors = errors
            };

            return View(newModel);
        }

        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Create(int userId, DateTime date)
        {
            if (userId < 1 || date == null) return View("Plan");

            var user = await _context.Users.FindAsync(userId);
            var beginningOfWeek = GetBeginningOfWeek(date);
            var endOfWeek = beginningOfWeek.AddDays(7);

            var availableTimes = await _context.AvailableWorktime
                .Where(t => t.UserId == user.Id)
                .Where(t => t.WorkDate >= beginningOfWeek)
                .Where(t => t.WorkDate <= endOfWeek)
                .ToListAsync();

            var plannedWorktimes = await _context.PlannedWorktime
                .Where(t => t.UserId == user.Id)
                .Where(t => t.WorkDate >= beginningOfWeek)
                .Where(t => t.WorkDate <= endOfWeek)
                .ToListAsync();

            var prognoses = await _context.Prognoses
                .Where(p => p.Date >= beginningOfWeek)
                .Where(p => p.Date <= endOfWeek)
                .ToListAsync();

            var model = new ScheduleCreateViewModel
            {
                AvailableWorkTimes = new List<AvailableWorktime>(),
                PlannedWorktimes = new List<PlannedWorktime>(),
                Prognoses = new List<Prognoses>(),
                MinimumDate = beginningOfWeek,
                MaximumDate = endOfWeek,
                UserName = user.GetFullName(),
                UserId = userId,
                Errors = _caoService.WorkWeekValidate(user, plannedWorktimes.ToArray())
            };

            for (int i = 0; i < 7; i++)
            {
                var day = beginningOfWeek.AddDays(i);

                model.AvailableWorkTimes.Add(availableTimes.Find(t => t.WorkDate == day));
                model.PlannedWorktimes.Add(plannedWorktimes.Find(p => p.WorkDate == day));
                model.Prognoses.Add(prognoses.Find(p => p.Date == day));
            }

            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Manager")]
        public async Task<IActionResult> Store(ScheduleCreateViewModel model)
        {
            var user = await _context.Users.FindAsync(model.UserId);
            model.Errors = _caoService.WorkWeekValidate(user, model.PlannedWorktimes.ToArray());

            foreach (var plannedWorktime in model.PlannedWorktimes)
            {
                var exists = await _context.PlannedWorktime
                    .AsNoTracking()
                    .Where(p => p.UserId == plannedWorktime.UserId)
                    .Where(p => p.WorkDate == plannedWorktime.WorkDate)
                    .AnyAsync();

                if (plannedWorktime.Start.TotalHours == 0 && plannedWorktime.Finish.TotalHours == 0)
                {
                    if (exists) _context.PlannedWorktime.Remove(plannedWorktime);
                    continue;
                }

                if (plannedWorktime.Start.TotalHours == 0 || plannedWorktime.Finish.TotalHours == 0)
                {
                    model.Errors.Add($"{plannedWorktime.WorkDate.ToShortDateString()} - Een van de tijden mist!");
                    break;
                }

                if (plannedWorktime.Start >= plannedWorktime.Finish)
                {
                    model.Errors.Add($"{plannedWorktime.WorkDate.ToShortDateString()} - Startijd kan niet hoger zijn dan eindtijd!");
                    break;
                }

                if (
                    plannedWorktime.Start.Hours < 6 ||
                    plannedWorktime.Finish.Hours > 23 ||
                    plannedWorktime.Start.Hours > 23 ||
                    plannedWorktime.Finish.Hours < 6
                )
                {
                    model.Errors.Add($"{plannedWorktime.WorkDate.ToShortDateString()} - Tijden mogen niet buiten 06:00 en 23:00 vallen!");
                    break;
                }              

                if (exists) _context.PlannedWorktime.Update(plannedWorktime);
                else await _context.PlannedWorktime.AddAsync(plannedWorktime);
            }

            await _context.SaveChangesAsync();

            if (model.Errors.Count > 0) return await ShowErrorsAsync(model);

            return RedirectToAction("Plan");
        }

        private async Task<IActionResult> ShowErrorsAsync(ScheduleCreateViewModel model)
        {
            var beginningOfWeek = GetBeginningOfWeek(model.MinimumDate);
            var endOfWeek = beginningOfWeek.AddDays(7);

            var availableWorktimes = await _context.AvailableWorktime
                .Where(t => t.UserId == model.UserId)
                .Where(t => t.WorkDate >= beginningOfWeek)
                .Where(t => t.WorkDate <= endOfWeek)
                .ToListAsync();

            var prognoses = await _context.Prognoses
                .Where(p => p.Date >= beginningOfWeek)
                .Where(p => p.Date <= endOfWeek)
                .ToListAsync();

            model.AvailableWorkTimes = new List<AvailableWorktime>();
            model.Prognoses = new List<Prognoses>();

            for (int i = 0; i < 7; i++)
            {
                var day = beginningOfWeek.AddDays(i);

                model.AvailableWorkTimes.Add(availableWorktimes.Find(t => t.WorkDate == day));
                model.Prognoses.Add(prognoses.Find(p => p.Date == day));
            }

            return View("Create", model);
        }

        private DateTime GetBeginningOfWeek(DateTime date)
        {
            return date.AddDays(-(int)date.DayOfWeek + (int)DayOfWeek.Monday);
        }

        private async Task<List<string>> CalculateMonthlyCAOAsync(List<User> users, DateTime date)
        {
            var errors = new List<string>();

            foreach (var user in users)
            {
                var plannedWorktimes = await _context.PlannedWorktime
                    .Where(t => t.UserId == user.Id)
                    .Where(t => t.WorkDate.Month == date.Month)
                    .ToListAsync();

                errors.AddRange(_caoService.WorkWeekValidate(user, plannedWorktimes.ToArray()));
            }

            return errors;
        }

        [HttpGet]
        public async Task<ActionResult<List<ScheduleResponseViewModel>>> GetPlannedWorkTime(DateTime start, DateTime end, int? id)
        {
            if (id == null || id == 0)
            {
                var user = await _userManager.FindByNameAsync(User.Identity.Name);
                id = user.Id;
            }

            var plannedWorktimes = await _context.PlannedWorktime
                .Where(p => p.WorkDate >= start)
                .Where(p => p.WorkDate <= end)
                .Where(p => p.UserId == id)
                .ToListAsync();

            var times = new List<ScheduleResponseViewModel>();

            foreach (var time in plannedWorktimes)
            {
                times.Add(new ScheduleResponseViewModel
                {
                    Title = $"Werken - {time.Section}",
                    Start = time.WorkDate.AddHours(time.Start.TotalHours),
                    End = time.WorkDate.AddHours(time.Finish.TotalHours)
                });
            }

            return times;
        }
    }
}

Bumbo.Web/Views/Schedule/Create.cshtml
@model Bumbo.Web.Models.ScheduleCreateViewModel

@{
    ViewData["Title"] = "Inplannen";
}

<h4>Inplannen voor @Model.UserName</h4>
<hr />

<div class="collapse" id="rules">
  <div class="card card-body">
    Zorg ervoor dat:
    <ul>
        <li>Werknemers niet meer dan 60 uur per week werken.</li>
        <li>Minderjarigen niet meer dan 8 uur per dag werken.</li>
        <li>Minderjarigen niet na dan 19:00 ingepland zijn.</li>
        <li>Minderjarigen niet meer dan 40 uur gemiddeld per week werken.</li>
        <li>Minderjarigen niet meer dan 12 uur zijn ingepland tijdens een schoolweek.</li>
        <li>Minderjarigen niet meer dan 5 dagen zijn ingepland per week.</li>
    </ul>
  </div>
</div>

<br>
<form asp-action="Store" asp-controller="Schedule" method="post">
    <input asp-for="UserId" type="hidden" value="@Model.UserId"/>
    <input asp-for="UserName" type="hidden" value="@Model.UserName"/>
    <input asp-for="MinimumDate" type="hidden" value="@Model.MinimumDate"/>
    <input asp-for="MaximumDate" type="hidden" value="@Model.MaximumDate"/>

    <div class="row">
        <div asp-validation-summary="None" class="text-danger"></div>

        @if (Model.Errors != null && Model.Errors.Count() > 0)
        {
            <div class="alert alert-danger" style="width: 100%" role="alert">
                <ul>
                    @foreach (var error in Model.Errors)
                    {
                        <li>@error</li>
                    }
                </ul>
            </div>
        }
    </div>
    <div class="row">
        
        <ul class="list-group col-6">

            <li class="list-group-item">
                <h5>Geplande tijden</h5>
            </li>

            @for (int i = 0; i < Model.PlannedWorktimes.Count(); i++)
            {
                <li class="list-group-item">
                    <div class="input-group">
                        <div class="input-group-prepend"><span class="input-group-text" id="">@Model.MinimumDate.AddDays(i).ToShortDateString()</span></div>

                        <input asp-for="@Model.PlannedWorktimes[i].UserId" value="@Model.UserId" type="hidden" />
                        <input asp-for="@Model.PlannedWorktimes[i].WorkDate" value="@Model.MinimumDate.AddDays(i)" type="hidden" />
                        
                        @if(Model.PlannedWorktimes[i] != null) 
                        {
                            <input step="900" value="@Model.PlannedWorktimes[i].Start" asp-for="@Model.PlannedWorktimes[i].Start" type="time" class="datetimepicker form-control">
                            <input step="900" value="@Model.PlannedWorktimes[i].Finish" asp-for="@Model.PlannedWorktimes[i].Finish" type="time" class="datetimepicker form-control">
                        }
                        else if (Model.AvailableWorkTimes[i] != null)
                        {
                            <input step="900" value="@Model.AvailableWorkTimes[i].Start" asp-for="@Model.PlannedWorktimes[i].Start" type="time" class="datetimepicker form-control">
                            <input step="900" value="@Model.AvailableWorkTimes[i].Finish" asp-for="@Model.PlannedWorktimes[i].Finish" type="time" class="datetimepicker form-control">
                        } 
                        else
                        {
                            <input step="900" asp-for="@Model.PlannedWorktimes[i].Start" type="time" class="datetimepicker form-control">
                            <input step="900" asp-for="@Model.PlannedWorktimes[i].Finish" type="time" class="datetimepicker form-control">
                        }
                        <select asp-for="@Model.PlannedWorktimes[i].Section" class="custom-select">
                            <option value="Kassa">Kassa</option>
                            <option value="Vriezer">Vriezer</option>
                            <option value="Vers">Vers</option>
                            <option value="Vakkenvullen">Vakkenvullen</option>
                            <option value="Anders">Anders</option>
                        </select>
                    </div>
                </li>
            }
        </ul> 

        <ul class="list-group col-6">

            <li class="list-group-item">
                <h5>Beschikbare tijden</h5>
            </li>

            @for (int i = 0; i < Model.AvailableWorkTimes.Count(); i++)
            {
                <li class="list-group-item">
                    @if (Model.AvailableWorkTimes[i] != null)
                    {
                        <div class="input-group">
                            <div class="input-group-prepend"><span class="input-group-text" id="">@Model.AvailableWorkTimes[i].WorkDate.ToShortDateString()</span></div>
                            
                            <input disabled value="@Model.AvailableWorkTimes[i].Start" type="time" class="datetimepicker form-control">
                            <input disabled value="@Model.AvailableWorkTimes[i].Finish" type="time" class="datetimepicker form-control">
                        </div>
                    } else
                    {
                        <div class="input-group">
                            <div class="input-group-prepend"><span class="input-group-text" id="">@Model.MinimumDate.AddDays(i).ToShortDateString()</span></div>
                            <input disabled type="time" class="datetimepicker form-control">
                            <input disabled type="time" class="datetimepicker form-control">
                        </div>
                    }
                </li>
            }
        </ul>   
        <br>
    </div>
    <div class="row my-4">
        <div class="col-6">
            <button class="btn btn-primary btn-lg btn-block" name="submitSchedule" type="submit">Planning opslaan</button>
        </div>
        <div class="col-6">
            <button class="btn btn-secondary btn-lg btn-block" type="button" data-toggle="collapse" data-target="#rules" aria-expanded="false" aria-controls="rules">CAO Regels</button>
        </div>
    </div>

    <div class="row mt-2">
        <h5>Prognose voor deze week</h5>
        <table class="table">
        <thead>
            <tr>
                <th scope="col">Datum</th>
                <th scope="col">Aantal Bezoekers</th>
                <th scope="col">Hoeveelheid Vracht</th>
                <th scope="col">Geschatte uren</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Prognoses.Count(); i++)
            {
            <tr>
                    @if (Model.Prognoses[i] != null)
                    {
                        <td>@Model.Prognoses[i].Date.ToShortDateString()</td>
                        <td>@Model.Prognoses[i].AmountOfCustomers bezoekers</td>
                        <td>@Model.Prognoses[i].AmountOfFreight vracht</td>
                        <td>@Model.Prognoses[i].GetEstimatedWorkingHours() uur</td>
                    } else {
                        <td>Geen prognose beschikbaar voor @Model.MinimumDate.AddDays(i).ToShortDateString()</td>
                    }
            </tr>
            }
        </tbody>
        </table>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Bumbo.Web/Views/Schedule/Index.cshtml
@model Bumbo.Web.Models.ScheduleViewModel

@{
    ViewData["Title"] = "Rooster";
}

<div class="row mb-4">
    <div class="col-12 d-flex justify-content-between align-items-center">
        <h4>Rooster</h4>
        @if (User.IsInRole("Manager"))
        {
            <form style="width: 512px" asp-action="Index" class="input-group">
                <div class="input-group-prepend">
                    <label id="userSelect" class="input-group-text">Rooster voor:</label>
                </div>
                <select onchange="this.form.submit()" asp-for="@Model.UserId" class="form-control" >
                    @foreach (var user in Model.Users)
                    {
                        <option value="@user.Id">@user.GetFullName()</option>
                    }
                </select>
            </form>
        }
    </div>
</div>

<div class="row">
    <div class="col-12">
        <div id="calendar"></div>
    </div>
</div>

<script>
const url = new URL(`${window.location.protocol}//${window.location.host}/Schedule/GetPlannedWorkTime`);
const id = @Model.UserId;

document.addEventListener('DOMContentLoaded', function () {
    const calendarElement = document.getElementById('calendar');
    const eventForm = document.getElementById('add-event');

    url.searchParams.append('id', id);

    $("#menu-toggle").click(function (e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });


    const calendar = new FullCalendar.Calendar(calendarElement, {
        headerToolbar: {
            left: 'prev,next today',
            center: 'title',
            right: ''
        },

        firstDay: 1,
        locale: 'nl',
        buttonText: {
            today: 'vandaag',
        },

        initialView: 'timeGridWeek',
        initialDate: new Date().toISOString().split('T')[0],

        nowIndicator: true,
        navLinks: true,
        editable: false,

        events: {
            url,
        }
    });

    calendar.render();
});
</script>

Bumbo.Web/Views/Schedule/Plan.cshtml
@model Bumbo.Web.Models.SchedulePlanViewModel

@{
    ViewData["Title"] = "Inplannen";
}

<div class="row">
    <div class="col-12 d-flex justify-content-between align-items-center">
        <h4>Inplannen</h4>
        <form style="width: 256px" asp-action="Plan" class="input-group">
            <div class="input-group-prepend">
                <label class="input-group-text" asp-for="@Model.Date">Week:</label>
            </div>
            <input id="week" onchange="this.form.submit()" type="date" asp-for="@Model.Date" class="form-control" />
        </form>
    </div>
</div>
<hr />

<div class="row">
    @if (Model.Errors != null && Model.Errors.Count() > 0)
    {
        <div class="alert alert-danger" style="width: 100%" role="alert">
            <ul>
                <li><b>De volgende CAO regels worden overschreden:</b></li>
                @foreach (var error in Model.Errors)
                {
                    <li>@error</li>
                }
            </ul>
        </div>
    }
</div>
<div class="row">
    <div class="col-12">
        <ul class="list-group">
        @foreach (var user in Model.Users)
        {
            <li class="list-group-item d-flex justify-content-between align-items-center">
                @user.GetFullName() 
                <form asp-action="Create" method="post">
                    <input type="hidden" name="userId" value="@user.Id" />
                    <input type="hidden" name="date" value="@Model.Date" />
                    <button type="submit" class="btn pull-right btn-primary">Inplannen</button>
                </form>
            </li>
        }
        </ul>   
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function () {
    const picker = document.getElementById('week');
    picker.min = new Date().toISOString().split("T")[0];
});
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}